#!/bin/sh
#
# Build Script
#
# This file is a hook script excuted while building.
# You can specify some commands to do.
# 
# NOTICE: You should return 0 when no error occurred.
#
# Copyright (C) 2015 Tiaozhan Net. All rights reserved.
#########################################################

set -e

. /usr/lib/log
info "Building start..."

#### NOW YOU CAN BEGIN FROM HERE ####

mv -f /runtime/config/website.conf /etc/nginx/website.conf

chmod 777 /dev/shm && \
ln -sf /dev/shm /runtime/tmp && \
rm -rf /runtime/APP/Application/Runtime && \
cp -rf /runtime/tmp /runtime/APP/Application/Runtime

#### THE END OF YOUR SCRIPT ####

info "Building complete."

exit



