#!/bin/sh
#
# Common Build Script
#
# This file is a hook script excuted before every building.
#
# Copyright (C) 2015 Tiaozhan Net. All rights reserved.
###########################################################

set -e

. /usr/lib/log

info "cBuild init"

if [ -f "/runtime/version" ]; then
    sed -i "s/build_date:.*/build_date: $(TZ='CST-8' date +%Y-%m-%d\ %T)/" /runtime/version
    cat /runtime/version >> /etc/version
    rm -f /runtime/version
else
    fatal "cannot find docker image version, you should run './configure' first, abort"
fi

chmod 755 /runtime/script -R

if [ -f "/runtime/script/build" ]; then
    eval "/runtime/script/build"
else
    info "cannot find build script at /runtime/script/build, skipped"
fi

info "cBuild complete."

exit