#!/bin/sh
#
# Pre-run script
#
# This file is a hook script excuted before running.
# You can specify some commands to do.
# 
# NOTICE: You should return 0 when no error occurred.
#
# Copyright (C) 2015 Tiaozhan Net. All rights reserved.
#########################################################

set -e

. /usr/lib/log

info "Pre-run start..."

#### NOW YOU CAN BEGIN FROM HERE ####

MODULE=${MODULE:-'uwsgifile'}
CALLABLE=${CALLABLE:-'app'}

info "MODULE  : ${MODULE}"
info "CALLABLE: ${CALLABLE}"

sed -e "s!MODULE!${MODULE}!g" -i /runtime/config/uwsgi.ini
sed -e "s!CALLABLE!${CALLABLE}!g" -i /runtime/config/uwsgi.ini

#### THE END OF YOUR SCRIPT ####

info "Pre-run complete."

exit
