#!/bin/sh
#
# Build Script
#
# This file is a hook script excuted while building.
# You can specify some commands to do.
# 
# NOTICE: You should return 0 when no error occurred.
#
# Copyright (C) 2015 Tiaozhan Net. All rights reserved.
#########################################################

set -e

. /usr/lib/log

info "Building start..."

#### NOW YOU CAN BEGIN FROM HERE ####

## init log and data and tmp dir
mkdir -p /runtime/APP /runtime/config /runtime/script /runtime/log /runtime/data
ln -sf /dev/shm /runtime/tmp
chmod 755 /runtime/data /runtime/log

## set default repo
mv -f /runtime/config/sources.list /etc/apt/sources.list

## set default timezone
apt-get update
echo "Asia/Shanghai" > /etc/timezone
apt-get install tzdata
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
apt-get clean
apt-get autoclean

#### THE END OF YOUR SCRIPT ####

info "Building complete."

exit