#!/bin/sh
#
# test script
#
# This file is a hook script excuted while testing.
# You can specify some commands to do.
# 
# NOTICE: You should return 0 when no error occurred.
#
# Copyright (C) 2017-2018 Tiaozhan Net. All rights reserved.
#########################################################

set -e

. /usr/lib/log

info "Testing start..."

#### NOW YOU CAN BEGIN FROM HERE ####

mkdir -p /runtime/APP/public
cat <<END >/runtime/APP/public/test.php
<?php
    echo "Hello, PHP7!\n";
?>
END

cat <<END >/tmp/supervisor.conf
[supervisord]
nodaemon=false
logfile=/runtime/log/supervisor.log

[program:nginx]
command=nginx -g "daemon off;"

[program:php-fpm]
command=/usr/sbin/php-fpm7 --nodaemonize
END

info "Starting supervisord..."
/usr/bin/supervisord -c /tmp/supervisor.conf 

sleep 3

nginx -V
php7 -v
php-fpm7 -v
echo "supervisord: "`supervisord -v`

curl -s localhost/test.php

#### THE END OF YOUR SCRIPT ####

info "Testing complete."

exit
