#!/bin/sh
#
# test script
#
# This file is a hook script excuted while testing.
# You can specify some commands to do.
# 
# NOTICE: You should return 0 when no error occurred.
#
# Copyright (C) 2015 Tiaozhan Net. All rights reserved.
#########################################################

set -e

. /usr/lib/log

info "Testing start..."

#### NOW YOU CAN BEGIN FROM HERE ####

cat <<END >/runtime/APP/uwsgifile.py
import flask
from flask import Flask
app = Flask(__name__)

@app.route("/version")
def hello():
    f = open("/runtime/log/test.log", "w")
    f.write("Hello Tenzor\n")
    f.close()
    return "\nHi. This is flask:"+flask.__version__+"\n:)\n\n"
END

cat <<END >/tmp/supervisor.conf
[supervisord]
nodaemon=false
logfile=/runtime/log/supervisor.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"

[program:uwsgi]
command=/usr/sbin/uwsgi /runtime/config/uwsgi.ini
END

info "Starting supervisord..."
/usr/bin/supervisord -c /tmp/supervisor.conf 

sleep 3

curl http://127.0.0.1/version
cat /runtime/log/test.log

#### THE END OF YOUR SCRIPT ####

info "Testing complete."

exit
